### PR TITLE
[Demo] try go mod

### LINKED ISSUE #85: Speed up docker build process
- need a new flow of pushing hot fix to dockerhub.
- try not to go get packages everytime.

### PR DESCRIPTION
**Pull request by ChihChengLiang**
### What was wrong?

This is an attempt to fix #85 by using the Go mod approach.

### How was it fixed?

By introducing `go.mod` and `go.sum`, the `go mod download` step in the `dev.Dockerfile` can cache the dependencies download, so no need to `go get` every time on codebase changes.

But there's an issue. The containers spun from the newly built images fails randomly when executing `add_peer` commands in Ansible scripts. The error message is:

```
dial attempt failed: connected to wrong peer. 
```

To reproduce this PR, one needs to

- upgrade Go to 1.11
- move the repo out of `$GOPATH`

#### Cute Animal Picture

image

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
It works for me on the first try. I'm using go1.11.1.

Note that I've updated my environment with 
```
go get -v ...
make deps # get latest gx
make partial-gx-rw
go build
```

**Comment by NIC619** [comment]
@jrhea I believe it's related to #100 and I'm currently working on the fix right now. Sorry for the trouble.

**Comment by jrhea** [comment]
@nic619 ahhh... interesting. Let me know if you have a fix and I will test it.  @ChihChengLiang I'll try your suggestion as well

**Comment by jrhea** [comment]
> @NIC619 ahhh... interesting. Let me know if you have a fix and I will test it. @ChihChengLiang I'll try your suggestion as well
> ```
> go get -v ...
> make deps # get latest gx
> make partial-gx-rw
> go build
>```
@ChihChengLiang still didn't work after performing those steps.  I am thinking that @NIC619 is on to something bc when add_peer fails, I get a message about connecting to a peer that doesn't exist (not in the list of peers i just spawned)

**Comment by ChihChengLiang** [comment]
Closed in favor of #121

**Pull request closed without merging**
